---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore
  labels:
    app.kubernetes.io/part-of: coolstore
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-cicd
  labels:
    app.kubernetes.io/part-of: coolstore
---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-virt
  labels:
    app.kubernetes.io/part-of: coolstore
---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-obs
  labels:
    app.kubernetes.io/part-of: coolstore
    openshift.io/cluster-monitoring: "true"
